--登陆错误码
LOGIN_ERROR_CODE = {}
LOGIN_ERROR_CODE.SUCCESS = 200
LOGIN_ERROR_CODE.USER_NOT_FOUND = 404
LOGIN_ERROR_CODE.UNAUTHORIZED = 401
LOGIN_ERROR_CODE.BAD_REQUEST = 400
LOGIN_ERROR_CODE.INDEX_EXPIRED = 403

LOGIN_ERROR_MSG = {}
LOGIN_ERROR_MSG[LOGIN_ERROR_CODE.SUCCESS] = "成功"
LOGIN_ERROR_MSG[LOGIN_ERROR_CODE.UNAUTHORIZED] = "未认证成功"
LOGIN_ERROR_MSG[LOGIN_ERROR_CODE.BAD_REQUEST] = "错误请求"
LOGIN_ERROR_MSG[LOGIN_ERROR_CODE.INDEX_EXPIRED] = "下标越界"
LOGIN_ERROR_MSG[LOGIN_ERROR_CODE.USER_NOT_FOUND] = "用户不存在"